# Generated by Django 4.2.16 on 2024-12-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('autor', models.CharField(max_length=255)),
                ('titulo', models.CharField(max_length=255)),
                ('year', models.TextField()),
                ('estado', models.TextField(blank=True, null=True)),
                ('resumen', models.TextField(blank=True, null=True)),
                ('created_at', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'articulos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, null=True)),
                ('important_fragment', models.TextField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('likes', models.IntegerField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'blog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PapersContent',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'papers_content',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Solicitudes',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('revisor', models.CharField(max_length=255)),
                ('articulo', models.CharField(max_length=255)),
                ('year', models.TextField()),
                ('estado', models.TextField(blank=True, null=True)),
                ('created_at', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'solicitudes',
                'managed': False,
            },
        ),
    ]
